export const academicPeriods = {
  items: [{ value: 'Abr 2021 / Ago 2021' }, { value: 'Oct 2021 / Feb 2022' }, { value: 'Abr 2022 / Ago 2022' }, { value: 'Oct 2022 / Feb 2023' }, { value: 'Abr 2023 / Ago 2023' }],
  defaultValue: 4,
}

export const provinces = {
  items: [
    { value: 'Azuay' },
    { value: 'Bolivar' },
    { value: 'Cañar' },
    { value: 'Carchi' },
    { value: 'Chimborazo' },
    { value: 'Cotopaxi' },
    { value: 'El Oro' },
    { value: 'Esmeraldas' },
    { value: 'Galapagos' },
    { value: 'Guayas' },
    { value: 'Imbabura' },
    { value: 'Loja' },
    { value: 'Los Rios' },
    { value: 'Manabí' },
    { value: 'Morona Santiago' },
    { value: 'Napo' },
    { value: 'No definido' },
    { value: 'Orellana' },
    { value: 'Pastaza' },
    { value: 'Pichincha' },
    { value: 'Santa Elena' },
    { value: 'Santo Domingo de los Tsáchilas' },
    { value: 'Sucumbíos' },
    { value: 'Tungurahua' },
    { value: 'Zamora Chinchipe' },
  ],
  defaultValue: 11,
}
