export const years = [{ value: '2023' }, { value: '2022' }, { value: '2021' }, { value: '2020' }]

export const provinces = [
  { value: 'Azuay' },
  { value: 'Bolivar' },
  { value: 'Cañar' },
  { value: 'Carchi' },
  { value: 'Chimborazo' },
  { value: 'Cotopaxi' },
  { value: 'El Oro' },
  { value: 'Esmeraldas' },
  { value: 'Galapagos' },
  { value: 'Guayas' },
  { value: 'Imbabura' },
  { value: 'Loja' },
  { value: 'Los Rios' },
  { value: 'Manabí' },
  { value: 'Morona Santiago' },
  { value: 'Napo' },
  { value: 'No definido' },
  { value: 'Orellana' },
  { value: 'Pastaza' },
  { value: 'Pichincha' },
  { value: 'Santa Elena' },
  { value: 'Santo Domingo de los Tsáchilas' },
  { value: 'Sucumbíos' },
  { value: 'Tungurahua' },
  { value: 'Zamora Chinchipe' },
]
