export const overViewTableheaders = [
  { name: '.' },
  { name: 'estudiante' },
  { name: 'fecha' },
  { name: 'materia' },
  { name: 'status' },
  { name: 'provincia' },
  { name: 'edad' },
  { name: 'sexo' },
  { name: 'discapacidad' },
  { name: 'reprobaciones' },
  { name: 'aab1' },
  { name: 'acdb1' },
  { name: 'apeb1' },
  { name: 'aab2' },
  { name: 'acdb2' },
  { name: 'apeb2' },
]

export const overViewStudents = [
  {
    name: 'Carlos Castillo',
    image: 'https://ui-avatars.com/api/?name=Carlos+Castillo&background=003f72&color=fff',
    identification: '1104999111',
    date: '14 Jul 2023',
    time: '16:20',
    subject: 'Procesos de Ingeniera de Software',
    status: 'Aprobada',
    province: 'Loja',
    age: 25,
    sex: 'H',
    disability: 'No',
    percentageDisability: 0,
    failures: 0,
    aab1: 8.71,
    acdb1: 10,
    apeb1: 10,
    aab2: 8.91,
    acdb2: 10,
    apeb2: 5,
  },
  {
    name: 'Luisa Diaz',
    image: 'https://ui-avatars.com/api/?name=Luis+Diaz&background=003f72&color=fff',
    identification: '1104999222',
    date: '13 Jul 2023',
    time: '14:10',
    subject: 'Ingeniería Web',
    status: 'Reprobada',
    province: 'Pichincha',
    age: 26,
    sex: 'M',
    disability: 'Si',
    percentageDisability: 25,
    failures: 2,
    aab1: 5.71,
    acdb1: 8,
    apeb1: 70,
    aab2: 5.91,
    acdb2: 3,
    apeb2: 0,
  },
  {
    name: 'Thalia Mijas',
    image: 'https://ui-avatars.com/api/?name=Thalia+Mijas&background=003f72&color=fff',
    identification: '1104999222',
    date: '12 Jul 2023',
    time: '11:09',
    subject: 'Programación Avanzada',
    status: 'Aprobada',
    province: 'Guayas',
    age: 27,
    sex: 'M',
    disability: 'No',
    percentageDisability: 0,
    failures: 2,
    aab1: 5.71,
    acdb1: 8,
    apeb1: 70,
    aab2: 5.91,
    acdb2: 3,
    apeb2: 0,
  },
  {
    name: 'Fernando Álvarez',
    image: 'https://ui-avatars.com/api/?name=Fernando+Alvarez&background=003f72&color=fff',
    identification: '1104999111',
    date: '11 Jul 2023',
    time: '16:20',
    subject: 'Sistemas Basados en Conocimiento',
    status: 'Aprobada',
    province: 'Azuay',
    age: 27,
    sex: 'H',
    disability: 'No',
    percentageDisability: 0,
    failures: 0,
    aab1: 8.71,
    acdb1: 10,
    apeb1: 10,
    aab2: 8.91,
    acdb2: 10,
    apeb2: 5,
  },
  {
    name: 'Karen Castillo',
    image: 'https://ui-avatars.com/api/?name=Karen+Castillo&background=003f72&color=fff',
    identification: '1104999222',
    date: '11 Jul 2023',
    time: '09:43',
    subject: 'Lógica de la Programación',
    status: 'Reprobada',
    province: 'Cotopaxi',
    age: 23,
    sex: 'M',
    disability: 'Si',
    percentageDisability: 5,
    failures: 2,
    aab1: 5.71,
    acdb1: 8,
    apeb1: 70,
    aab2: 5.91,
    acdb2: 3,
    apeb2: 0,
  },
]
