export const enrollmentInputs = {
  data: [
    {
      size: 'col-span-6 md:col-span-2',
      label: 'Identificación',
      type: 'text',
      required: true,
      id: 'identification',
      name: 'identification',
      placeholder: 'Ej. 1101XXXXXX',
    },
    {
      size: 'col-span-6 md:col-span-2',
      label: 'Nombres',
      type: 'text',
      required: true,
      id: 'name',
      name: 'name',
      placeholder: 'Ej. Matias Antonio',
    },
    {
      size: 'col-span-6 md:col-span-2',
      label: 'Apellidos',
      type: 'text',
      required: true,
      id: 'lastname',
      name: 'lastname',
      placeholder: 'Ej. Rodriguez Perez',
    },
    {
      size: 'col-span-6 md:col-span-2',
      label: 'Edad',
      type: 'number',
      required: false,
      id: 'age',
      name: 'age',
      placeholder: 'Ej. 23',
      inputText: 'años',
      min: 0,
      max: 100,
    },
    {
      size: 'col-span-6 md:col-span-2',
      label: 'Sexo',
      type: 'select',
      required: false,
      id: 'sex',
      name: 'sex',
      placeholder: 'Seleccione un sexo',
      items: [{ value: 'Hombre' }, { value: 'Mujer' }],
      defaultValue: -1,
      searchable: false,
    },
    {
      size: 'col-span-6 md:col-span-2',
      label: 'Provincia de nacimiento',
      type: 'select',
      required: true,
      id: 'province',
      name: 'province',
      placeholder: 'Seleccione una provincia',
      items: [
        { value: 'Azuay' },
        { value: 'Bolivar' },
        { value: 'Cañar' },
        { value: 'Carchi' },
        { value: 'Chimborazo' },
        { value: 'Cotopaxi' },
        { value: 'El Oro' },
        { value: 'Esmeraldas' },
        { value: 'Galapagos' },
        { value: 'Guayas' },
        { value: 'Imbabura' },
        { value: 'Loja' },
        { value: 'Los Rios' },
        { value: 'Manabí' },
        { value: 'Morona Santiago' },
        { value: 'Napo' },
        { value: 'No definido' },
        { value: 'Orellana' },
        { value: 'Pastaza' },
        { value: 'Pichincha' },
        { value: 'Santa Elena' },
        { value: 'Santo Domingo de los Tsáchilas' },
        { value: 'Sucumbíos' },
        { value: 'Tungurahua' },
        { value: 'Zamora Chinchipe' },
      ],
      defaultValue: -1,
      searchable: true,
    },
  ],
}
