export const enrollmentInputs = {
  data: [
    {
      size: 'col-span-6 md:col-span-3',
      label: 'Identificación',
      type: 'text',
      required: true,
      id: 'identification',
      name: 'identification',
      placeholder: 'Ej. 1101XXXXXX',
    },
    {
      size: 'col-span-6 md:col-span-3',
      label: 'Nombres',
      type: 'text',
      required: true,
      id: 'name',
      name: 'name',
      placeholder: 'Ej. Matias Antonio',
    },
    {
      size: 'col-span-6 md:col-span-3',
      label: 'Apellidos',
      type: 'text',
      required: true,
      id: 'lastname',
      name: 'lastname',
      placeholder: 'Ej. Rodriguez Perez',
    },
    {
      size: 'col-span-6 md:col-span-1',
      label: 'Edad',
      type: 'number',
      required: false,
      id: 'age',
      name: 'age',
      placeholder: 'Ej. 23',
      inputText: 'años',
      min: 0,
      max: 100,
    },
    {
      size: 'col-span-6 md:col-span-2',
      label: 'Sexo',
      type: 'select',
      required: false,
      id: 'sex',
      name: 'sex',
      placeholder: 'Seleccione un sexo',
      items: [{ value: 'Hombre' }, { value: 'Mujer' }],
      defaultValue: -1,
      searchable: false,
    },
  ],
}
