import { listPeriods, listSubjects } from '@services/api/classify'

export const getGradesInputs = async () => {
  const subjects = await listSubjects()
  const periodos = await listPeriods()
  const gradesInputs = {
    data: [
      {
        size: 'col-span-6 md:col-span-2',
        label: 'Materia',
        type: 'select',
        required: true,
        id: 'subject',
        name: 'subject',
        placeholder: 'Seleccione una materia',
        items: subjects.data,
        defaultValue: -1,
        searchable: true,
      },
      {
        size: 'col-span-6 md:col-span-2',
        label: 'Periodo académico',
        type: 'select',
        required: true,
        id: 'academicPeriod',
        name: 'academicPeriod',
        placeholder: 'Seleccione un periodo académico',
        items: periodos.data,
        defaultValue: -1,
        searchable: true,
      },
      {
        size: 'col-span-6 md:col-span-2',
        label: 'Número de reprobaciones',
        type: 'number',
        required: true,
        id: 'numberFailures',
        name: 'numberFailures',
        placeholder: 'Ej. 0',
        min: 0,
      },
      {
        size: 'col-span-3 md:col-span-2',
        label: 'AAB1',
        type: 'number',
        required: false,
        id: 'aab1',
        name: 'aab1',
        placeholder: 'Ej. 0',
        inputText: '/ 10',
        min: 0,
        max: 10,
      },
      {
        size: 'col-span-3 md:col-span-2',
        label: 'ACDB1',
        type: 'number',
        required: false,
        id: 'acbd1',
        name: 'acdb1',
        placeholder: 'Ej. 0',
        inputText: '/ 10',
        min: 0,
        max: 10,
      },
      {
        size: 'col-span-3 md:col-span-2',
        label: 'APEB1',
        type: 'number',
        required: false,
        id: 'apeb1',
        name: 'apeb1',
        placeholder: 'Ej. 0',
        inputText: '/ 10',
        min: 0,
        max: 10,
      },
      {
        size: 'col-span-3 md:col-span-2',
        label: 'AAB2',
        type: 'number',
        required: false,
        id: 'aab2',
        name: 'aab2',
        placeholder: 'Ej. 0',
        inputText: '/ 10',
        min: 0,
        max: 10,
      },
      {
        size: 'col-span-3 md:col-span-2',
        label: 'ACDB2',
        type: 'number',
        required: false,
        id: 'acbd2',
        name: 'acdb2',
        placeholder: 'Ej. 0',
        inputText: '/ 10',
        min: 0,
        max: 10,
      },
      {
        size: 'col-span-3 md:col-span-2',
        label: 'APEB2',
        type: 'number',
        required: false,
        id: 'apeb2',
        name: 'apeb2',
        placeholder: 'Ej. 0',
        inputText: '/ 10',
        min: 0,
        max: 10,
      },
    ],
  }

  return gradesInputs
}
